In [1]:
import numpy as np

### Paso 1: Intentemos realizar una suma entre dos listas

In [2]:
# Creamos dos listas
a = [1,2,3,4,5]
b = [6,7,8,9,0]

In [3]:
# Mostramos el contenido de las listas
print(a)
print(b)

[1, 2, 3, 4, 5]
[6, 7, 8, 9, 0]


In [4]:
# Intentamos realizar una operación de suma entre las dos listas
c = a+b
print(c)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]


#### El resultado es la concatenación de las dos listas

### Paso 2: Intentemos hacer lo mismo pero esta vez utilizando arrays con numpy

In [5]:
# Creados dos arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,0])

In [6]:
# Mostramos el contenidos de ambos arrays
print(a)
print(b)

[1 2 3 4 5]
[6 7 8 9 0]


In [7]:
c = a+b
print(c)

[ 7  9 11 13  5]


#### El resultado es la suma de cada uno de sus elementos
1 + 6 = 7<br>
2 + 7 = 9<br>
3 + 8 = 11<br>
4 + 9 = 13<br>
5 + 0 = 0<br>