In [1]:
import numpy as np

In [2]:
# Creamos una matriz con valores auto-completados
matriz = np.arange(24).reshape(4,6)
print(matriz)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [4]:
# Consultamos un valor en especial (16)
print(matriz[2,4])
    # Recordemos que siempre iniciamos en 0 tanto por fila como por columna

16
